---
# From: https://github.com/Ekumen-OS/andino/tree/jazzy/andino_hardware
#
- name: Install RPi Camera dependencies
  apt:
    pkg:
      - libraspberrypi-bin
      - v4l-utils
      - raspi-config
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Add user to dialout group to be able to use serial ports and camera
  user:
    name: "{{ ansible_user }}"
    groups: "dialout,plugdev,video"
    append: yes
  become: true

- name: Read RPi camera status
  shell: vcgencmd get_camera
  register: camera_state
  changed_when: false

- name: Check if RPi camera is installed and working
  set_fact:
    warnings: "{{ warnings + ['RPi camera not detected'] }}"
  when: "'supported=1 detected=1' not in camera_state"

- name: Configure RPi camera if it isn't detected
  command: sudo raspi-config nonint do_camera 1
  when: "'supported=1 detected=1' not in camera_state"

- name: Configure serial port names for Arduino and Lidar
  blockinfile:
    path: /etc/udev/rules.d/10-usb-serial.rules
    create: true
    content: |
        SUBSYSTEM=="tty", ATTRS{idProduct}=="{{ arduino_serial.id_product }}", ATTRS{idVendor}=="{{ arduino_serial.id_vendor }}", SYMLINK+="ttyUSB_ARDUINO"
        SUBSYSTEM=="tty", ATTRS{idProduct}=="{{ lidar_serial.id_product }}", ATTRS{idVendor}=="{{ lidar_serial.id_vendor }}", SYMLINK+="ttyUSB_LIDAR"
  become: true
  register: usb_serial_rules

- name: "Reload udev rules"
  shell: udevadm control --reload-rules && udevadm trigger
  become: true
  when: usb_serial_rules.changed

- name: Verify custom Arduino serial port exists
  stat:
    path: "/dev/{{ arduino_serial.name }}"
  register: arduino_serial_result
  failed_when: not arduino_serial_result.stat.exists

- name: Verify custom Lidar serial port exists
  stat:
    path: "/dev/{{ lidar_serial.name }}"
  register: lidar_serial_result
  failed_when: not lidar_serial_result.stat.exists

- name: Install PlatformIO dependencies
  apt:
    name: python3-venv
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Download PlatformIO installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
    dest: /tmp/get-platformio.py

- name: Install PlatformIO
  command: python3 /tmp/get-platformio.py

- name: Add PlatformIO to the PATH
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export PATH=$PATH:/home/{{ ansible_user }}/.platformio/penv/bin"
