---
# From: https://github.com/Ekumen-OS/andino/tree/jazzy?tab=readme-ov-file#build-from-source

- name: Create the Andino workspace
  file:
    dest: "{{ andino_workspace_path }}/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone the Andino Github repository
  git:
    repo: "{{ andino_github_repo }}"
    dest: "{{ andino_workspace_path }}/src"
    version: "{{ ros2_distribution }}"
    accept_hostkey: true
    single_branch: true

- name: Install Andino dependencies via rosdep
  shell: |
    source /opt/ros/{{ ros2_distribution }}/setup.bash &&
    rosdep install --from-paths {{ andino_workspace_path }}/src --ignore-src -y
  register: rosdep_install_result
  changed_when: "rosdep_install_result.stdout != '#All required rosdeps installed successfully'"
  args:
    executable: /bin/bash

- name: Build the Andino workspace with colon
  shell: source /opt/ros/{{ ros2_distribution }}/setup.bash && colcon build
  args:
    chdir: "{{ andino_workspace_path }}"
    executable: /bin/bash
    creates: install/setup.bash

- name: Update .bashrc with install/setup.bash
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: source {{ andino_workspace_path }}/install/setup.bash
    state: present
    insertbefore: "# BEGIN ANSIBLE MANAGED BLOCK"
    firstmatch: true
