---
- name: Run Andino Hardware tasks
  import_tasks: 00-andino_hardware.yaml
  tags: skip_ci

- name: Install Andino packages via debians
  import_tasks: 01-andino_debians.yaml
  when: not andino_install_from_sources

- name: Install Andino packages from sources
  import_tasks: 02-andino_sources.yaml
  when: andino_install_from_sources or andino_extra_sources | length > 0
